=head1 NAME

FlexibleTicketModule

=head1 DESCRIPTION

If you need more dialogs for the ticket zoom, e.g. if you want to add new dialogs to handle visits at the
customers' site, you can use this addon to define those dialogs.

All the dialogs are based on the AgentTicketPhoneOutbound, but you can define several things like
article type, the fields shown etc. In the SysConfig you get two sample configs, but you can define 
more dialogs in your own xml file.

=head1 REPOSITORY AND BUGTRACKER

The code repository and a bugtracker are available at L<http://github.com/reneeb/otrs-FlexibleTicketModule>.

=head1 AUTHOR

Renee Baecker C<< <info@feature-addons.de> >>

