=head1 NAME

AdditionalToolbarSearchFields

=head1 DESCRIPTION

In stock OTRS you can enable a fulltext search in the toolbar. With this addon you can add an additional field to
search for the customer number.

Additionally you can enable a form where the search is limited to the "open" ticket states.

=head1 REPOSITORY AND BUGTRACKER

The code repository and a bugtracker are available at L<http://github.com/reneeb/otrs-AdditionalToolbarSearchFields>.

=head1 ACKNOWLEDGEMENT

This addon was sponsored by SIJN ICT Services (L<http://sijn.nl>).

=head1 AUTHOR

Renee Baecker C<< <info@feature-addons.de> >>

